### PR TITLE
Some tweaks to data connector resource

### PR DESCRIPTION
**Pull request by davidji99**
One not so insignificant change introduced in this PR is an easier method to import data connectors using a composite value of `APP_NAME:DATA_CONNECTOR_NAME`.

Also need to add a loop to verify data connector settings are successfully updated.

----

- [x] Test creating data connectors
- [x] Test importing data connectors

### CODE REVIEW

**Comment by davidji99** [comment]
@jonstacks,

Curious when updating data connector settings via TF, have you been getting a dirty `plan` diff afterwards? Currently there's no loop to verify the changes after updating connector settings so the provider will set whatever is returned when querying the data connector.

It seems it takes some undocumented time for the updated settings to be properly reflected in Heroku. Did you experience this?

**Comment by jonstacks** [comment]
@davidji99,

Yes, I was getting a dirty plan for a few minutes afterwards. Running a `terraform apply` would return a `422 Unprocessable Entity`, if I'm remembering correctly, stating that a modification was already in progress. If you want me to look at updating it to poll for completion, I can give that a try.

**Comment by davidji99** [comment]
> Running a `terraform apply` would return a `422 Unprocessable Entity`, if I'm remembering correctly, stating that a modification was already in progress.

Yeah, there's no indication in the API response that tells the status of the settings update. Not ideal but the resource just needs to check the `settings` attribute value with what's present remotely.



> If you want me to look at updating it to poll for completion, I can give that a try.

All good! I had something in the works already. Feel free to try out this branch locally if you'd like.

**Review by jonstacks — APPROVED** [review]
:+1: Looks great.

**Comment by jonstacks** [comment]
I'll try to test this locally in the next few days.

**Comment by davidji99** [comment]
> I'll try to test this locally in the next few days.

Thanks. Appreciate it!

**Comment by jonstacks** [comment]
@davidji99 it worked great!

```
herokux_data_connector.my_hc_staging: Modifying... [id=11111-11111-111111-1111]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 10s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 20s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 30s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 40s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 50s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 1m0s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 1m10s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 1m20s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 1m30s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 1m40s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 1m50s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 2m0s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 2m10s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 2m20s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 2m30s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 2m40s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 2m50s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 3m0s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 3m10s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 3m20s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 3m30s elapsed]
herokux_data_connector.my_hc_staging: Still modifying... [id=11111-11111-111111-1111, 3m40s elapsed]
herokux_data_connector.my_hc_staging: Modifications complete after 3m48s [id=11111-11111-111111-1111]
```

Only error I got was around updating the provider timeouts to match the new code, but I think that is expected.

```
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...

Error: Unsupported argument

  on backend.tf line 18, in provider "herokux":
  18:     data_connector_update_timeout = 20

An argument named "data_connector_update_timeout" is not expected here.
```

**Comment by davidji99** [comment]
@jonstacks 

Great to hear! Thanks for testing this out. I'll do some minor cleanup and make a release.

And yeah the error you encountered is expected. I renamed `data_connector_update_timeout` to `data_connector_status_update_timeout` when I introduced `data_connector_settings_update_timeout`. This is to provide more granularity for the user to define timeouts when updating different attributes of the data connector.

**Pull request merged**
